import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: "#ffffff" },
  container: {
    alignSelf: "center",
    width: "100%",
    maxWidth: 1200,
    padding: 16,
    paddingBottom: 60,
    backgroundColor: "#ffffff",
    gap: 10,
  },

  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 8,
    marginBottom: 6,
  },
  title: {
    fontSize: 28,
    fontWeight: "800",
    color: "#c1121f",
    lineHeight: 34,
  },

  row: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    alignItems: "center",
    marginTop: 6,
  },

  btn: {
    backgroundColor: "#c1121f",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    shadowColor: "#c1121f",
    shadowOpacity: 0.25,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  btnPressed: { transform: [{ translateY: -2 }], shadowOpacity: 0.35 },
  btnText: { color: "#ffffff", fontWeight: "700", fontSize: 14 },

  sectionTitle: {
    marginTop: 18,
    marginBottom: 8,
    fontSize: 18,
    fontWeight: "800",
    color: "#c1121f",
  },
  subTitle: {
    marginTop: 12,
    marginBottom: 6,
    fontSize: 14,
    fontWeight: "800",
    color: "#9b111e",
  },

  practiceList: { marginTop: 8, maxHeight: 170 },
  practiceItem: {
    backgroundColor: "#ffffff",
    borderRadius: 14,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
    borderLeftWidth: 6,
    borderLeftColor: "#e63946",
  },
  practiceItemSelected: { borderLeftColor: "#c1121f", backgroundColor: "#fff5f5" },
  practiceText: { color: "#1f2933", fontSize: 13, fontWeight: "600" },

  chartCard: {
    marginTop: 18,
    padding: 16,
    backgroundColor: "#ffffff",
    borderRadius: 14,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 3,
    borderTopWidth: 5,
    borderTopColor: "#c1121f",
    gap: 12,
  },
  chartWrap: {
    width: "100%",
    height: 320,
    position: "relative",
    borderRadius: 10,
    overflow: "hidden",
  },
  selectionOverlay: {
    position: "absolute",
    top: 0,
    bottom: 0,
    backgroundColor: "rgba(193, 18, 31, 0.18)",
    borderColor: "rgba(193, 18, 31, 0.55)",
    borderWidth: 1,
    zIndex: 10,
  },

  card: {
    marginTop: 18,
    backgroundColor: "#ffffff",
    borderRadius: 14,
    padding: 16,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
    borderLeftWidth: 6,
    borderLeftColor: "#e63946",
    gap: 6,
  },

  text: { marginVertical: 2, fontSize: 14, color: "#1f2933" },
  bold: { color: "#c1121f", fontWeight: "800" },
  empty: { marginTop: 14, fontStyle: "italic", color: "#6b7280" },

  listBlock: { marginTop: 8, gap: 10 },
  listRow: {
    backgroundColor: "#f9fafb",
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: "#f1f5f9",
  },
});